# Generated by Django 6.0.2 on 2026-02-16 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('source_video', 'Source Video'), ('logo', 'Logo'), ('font', 'Font')], max_length=20)),
                ('file', models.FileField(upload_to='assets/%Y/%m/%d')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('draft_video', models.FileField(blank=True, upload_to='drafts/%Y/%m/%d')),
                ('timeline_json', models.JSONField(blank=True, default=dict)),
                ('approved', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('prompt', models.TextField(blank=True)),
                ('template_id', models.CharField(default='hook_benefit_cta_v1', max_length=80)),
                ('primary_color', models.CharField(default='#00A86B', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('draft_ready', 'Draft Ready'), ('exported', 'Exported'), ('failed', 'Failed')], default='created', max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overlay_type', models.CharField(choices=[('headline', 'Headline'), ('cta', 'CTA'), ('logo', 'Logo'), ('sticker', 'Sticker'), ('callout', 'Callout'), ('endcard', 'End Card')], max_length=16)),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('text', models.CharField(blank=True, max_length=240)),
                ('position', models.JSONField(blank=True, default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.asset')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='projects.draft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('generate_draft', 'Generate Draft'), ('export_final', 'Export Final')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('task_id', models.CharField(blank=True, max_length=80)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='exports/%Y/%m/%d')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='projects.draft')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='projects.project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'asset_type'], name='projects_as_project_663f59_idx'),
        ),
    ]
