# Generated by Django 6.0.2 on 2026-02-17 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('source', models.CharField(default='unknown', max_length=32)),
                ('timeline_json', models.JSONField(blank=True, default=dict)),
                ('overlay_diff_json', models.JSONField(blank=True, default=dict)),
                ('draft_video_name', models.CharField(blank=True, max_length=255)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.draft')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'version'), name='unique_draft_version')],
            },
        ),
    ]
