# Generated by Django 6.0.2 on 2026-02-17 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_videocontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPlanArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('source', models.CharField(default='auto', max_length=32)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('quality_report_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_plans', to='projects.draft')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_plans', to='projects.project')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('project', 'version'), name='unique_project_edit_plan_version')],
            },
        ),
    ]
